services:
  stock-tracker-app:
    container_name: stock-tracker-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    depends_on:
      stock-tracker-db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    restart: unless-stopped

  stock-tracker-db:
    container_name: stock-tracker-db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - stock_tracker_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  stock_tracker_db:
